### ISSUE TITLE
Add specs for likes_controller_spec.rb

### ISSUE THREAD

**Issue by AlexAvlonitis** [AlexAvlonitis/kardies#24]
Add rspec spec for https://github.com/AlexAvlonitis/kardies/blob/master/app/controllers/api/v1/likes_controller.rb file.

https://github.com/AlexAvlonitis/kardies/blob/master/spec/controllers/api/v1/users_controller_spec.rb  -> for reference

**Comment by cassianoblonski** [comment]
trying this one

**Comment by eric-kovshovik** [comment]
☝️ done! Let me know if anythings needs correction there
