### ISSUE TITLE
Add spec for conversations_controller.rb

### ISSUE THREAD

**Issue by AlexAvlonitis** [AlexAvlonitis/kardies#25]
Add rspec spec for -> https://github.com/AlexAvlonitis/kardies/blob/master/app/controllers/api/v1/conversations_controller.rb

https://github.com/AlexAvlonitis/kardies/blob/master/spec/controllers/api/v1/users_controller_spec.rb -> for reference

**Comment by philiplambok** [comment]
I'll take this

**Comment by ducmtran** [comment]
Hey can I take this issue? :D

**Comment by AlexAvlonitis** [comment]
For sure @ducmtran

**Comment by ducmtran** [comment]
Just gonna leave it here that I might be slow on this so if anyone can beat me to it then feel free!

**Comment by ngsikai** [comment]
@ducmtran @AlexAvlonitis Added some short tests for conversations controller while referencing user controller as suggested. Do take a look and leave some comments and whether it looks okay 😄
