### ISSUE TITLE
Add spec for messages_controller.rb

### ISSUE THREAD

**Issue by AlexAvlonitis** [AlexAvlonitis/kardies#26]
Add rspec spec for -> https://github.com/AlexAvlonitis/kardies/blob/master/app/controllers/api/v1/messages_controller.rb

https://github.com/AlexAvlonitis/kardies/blob/master/spec/controllers/api/v1/users_controller_spec.rb -> for reference

There is an open issue to fix the failing build/tests, ignore other tests just focus to pass this one.

**Comment by smowafy** [comment]
I will take this if possible
