### ISSUE TITLE
Add controller spec for reports_controller.rb

### ISSUE THREAD

**Issue by AlexAvlonitis** [AlexAvlonitis/kardies#29]
Add rspec spec for reports_controller file-> https://github.com/AlexAvlonitis/kardies/blob/master/app/controllers/api/v1/reports_controller.rb

spec for reference -> 
https://github.com/AlexAvlonitis/kardies/blob/master/spec/controllers/api/v1/users_controller_spec.rb

**Comment by mvbvieira** [comment]
hi Alex, i can make the tests

**Comment by eric-kovshovik** [comment]
☝️ I hope it helps!

**Comment by eric-kovshovik** [comment]
#31 is ready to be merged!

**Comment by AlexAvlonitis** [comment]
awesome @eric-kovshovik
