### ISSUE TITLE
Add specs for EmailPreferencesController

### ISSUE THREAD

**Issue by AlexAvlonitis** [AlexAvlonitis/kardies#33]
add rspec spec for https://github.com/AlexAvlonitis/kardies/blob/master/app/controllers/api/v1/email_preferences_controller.rb

for reference -> https://github.com/AlexAvlonitis/kardies/blob/master/spec/controllers/api/v1/users_controller_spec.rb

**Comment by sathia27** [comment]
@AlexAvlonitis  I would like to pick this up?

**Comment by AlexAvlonitis** [comment]
Sure thing @sathia27 !

**Comment by sathia27** [comment]
@AlexAvlonitis can you please review pull request which is raised. Let me know if something is missing from my end.
