### ISSUE TITLE
key not found: "S3_BUCKET_NAME"

### ISSUE THREAD

**Issue by sundaleek** [AlexAvlonitis/kardies#51]
I'm new to Ruby and BE dev, can you clarify in more details how to run locally this site? 

I found error
/Users/dmozmanyan/Downloads/kardies-master/config/environments/development.rb:6:in `fetch': key not found: "S3_BUCKET_NAME" (KeyError)
While installing command 'bundle exec puma'
Can you help me to understand what is the issue?

**Comment by AlexAvlonitis** [comment]
hey @sundaleek - Copy the .env.example file and paste to .env and change the variables to yours. for the S3 you might need to create an aws s3 account if you want to test the image uploading, otherwise just leave it blank

**Comment by sundaleek** [comment]
@AlexAvlonitis   I want to develop my backend API server for iOS app start-up, can you recommend courses or resources/libraries how to achieve that as fast as possible? Thank you very much

**Comment by AlexAvlonitis** [comment]
Hey @sundaleek try ruby on rails , you can learn from youtube and udemy.com
